name: Deploy Plugin via REST API and Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip the plugin folder
        run: zip -r helloextend-protection.zip helloextend-protection

      - name: Upload plugin via WordPress REST API
        run: |
          curl -X POST "https://woocommerce.woodys.extend.com/wp-json/wp/v2/plugins" \
          -u "${{ secrets.WP_ADMIN_AUTH }}" \
          -F "plugin=@helloextend-protection.zip"

      - name: Install and activate plugin
        run: |
          curl -X POST "https://woocommerce.woodys.extend.com/wp-json/wp/v2/plugins/helloextend-protection/activate" \
          -u "${{ secrets.WP_ADMIN_AUTH }}"

      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress tests
        run: npx cypress run
